title: Kirthana
description: >-
  ECE Student specializing in VLSI Design, 
  AI-ML and Embedded Systems. Passionate about hardware-software co-design, AI Hardware, 
  and sustainable manufacturing. love to innovate!🛠️💡

theme: jekyll-theme-minimal

# Site Settings
author: Kirthana P Rao
email: work.kirthana@gmail.com

baseurl: "" # Leave empty for username.github.io
url: "https://kirthana1181.github.io" # Replace with your actual GitHub username

# Social Links
social_links:
    - { platform: github,   user_url: "https://github.com/kirthana1181" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/kirthana-p-6b89b326b" }
    - { platform: email,    user_url: "mailto:work.kirthana@gmail.com" }


# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
header_pages:
  - about.md
  - projects.md
  - experience.md
  - skills.md
  - contact.md

# Collections for organizing content
collections:
  projects:
    output: true
    permalink: /projects/:name/
  certifications:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
